name: HeroCraft
version: '${project.version}'
main: de.christoph.herocraft.HeroCraft
api-version: '1.20'
depends: 'EntitySize'

commands:
  setprisonspawn:
  freeprison:
  prison:
  farmwelt:
    aliases:
      - farmworld
  landmobs:
  provocateraid:
  landpunkte:
  moblist:
  semitrust:
  semiuntrust:
  dimensionstorage:
    aliases:
      - storage
      - kiste
      - dimensionkiste
  createtutorialvideo:
  createcity:
  challenge:
  landtag:
  tagfarbe:
  floristmarket:
  besondereitems:
  birthday:
  coins:
    aliases:
      - coin
      - befehle
      - economy
      - money
  befehle:
    aliases:
      - commands
      - hilfe
      - help
  spawn:
  chatclear:
    aliases:
      - clearchat
      - cc
  broadcast:
  enderchest:
    aliases:
      - ec
      - endertruhe
  gamemode:
    aliases:
      - gm
  hut:
    aliases:
      - hat
  inventar:
    aliases:
      - inventory
      - inv
      - invsee
  verzaubern:
    aliases:
      - enchantment
  umbennenen:
    aliases:
      - rename
  signieren:
    aliases:
      - sign
  tpa:
    aliases:
      - teleportanfrage
  vanish:
    aliases:
      - v
  sprung:
  adminafk:
  dimensions:
  home:
  message:
    aliases:
      - msg
      - nachricht
  reply:
    aliases:
      - antwort
      - r
  rtp:
  teleporter:
    aliases:
      - warps
      - warp
      - tpter
      - teleportieren
      - navigator
      - navigation
  setcasewinnings:
  trust:
  untrust:
  endraid:
  gratisanycoins:
  killalltroops:
  taeglichequest:
  createlandfast:
  setpresentationholo:
  landvote:
  auktionshaus:
  createland:
    aliases:
      - landerstellen
      - neuesland
  land:
  landshop:
  moebelhaus:
  landeinladungannehmen:
  landeinladungablehnen:
  tutorialnpc:
  tutorialnein:
  starttutorial:
  startonboarding:
  createtutoriallandposition:
  markttutorial:
  marktnein:
  startmehrinfos:
  forschungsergebnis:
  rezepte:
  versicherungen:
  startvoteday:
  tagja:
  tagnein:
  mentor:
  status:
  booster:
  fishmarket:
  woodmarket:
  minermarket:
  butchermarket:
  armorermarket:
  monsterdrops:
  animaldrops:
  job:
    aliases:
      - jobs
      - beruf
  statistiken:
    aliases:
      - stats
      - statistik